feat: add referrals page
storacha/storacha.network pull request #81
Opened 2024-11-16 00:38 UTC by travis

Based on Figma mockups. Uses a simple form to send users to the console - VUE_APP_CONSOLE_URL should be set to https://console.storacha.network in production.

<img width="1223" alt="Screenshot 2024-11-15 at 4 38 26 PM" src="https://github.com/user-attachments/assets/f2602971-0a26-40b9-ae00-51f2032a2fed">
<img width="1229" alt="Screenshot 2024-11-15 at 4 38 33 PM" src="https://github.com/user-attachments/assets/42831368-8bbf-4c19-a39c-cca63e80c80b">

2024-11-20 16:13 UTC, cwaring requested changes
hey @travis, I spotted a couple of errors here and added some review notes.

also for consistency and responsive behaviour I'd suggest using the other frame of the body split component to hold the form element instead of the header, but ultimately a stylistic choice here :)

2024-11-20 16:13 UTC, cwaring commented on app.config.ts
> +      { text: 'Referrals', href: 'https://storacha.network/referrals' },
```suggestion
      { text: 'Referrals', href: '/referrals' },
```
internal app pages should be relative

2024-11-20 16:13 UTC, cwaring commented on components/ReferralCodeCreator.vue
> +const referralsUrl =  `${process.env.VUE_APP_CONSOLE_URL}/referrals`
`process.env` will not be available for es modules after build, you should use `import.meta.env` instead where required: https://nuxt.com/docs/api/advanced/import-meta#builder-properties

2024-12-04 16:58 UTC, fforbeck approved these changes
LGTM!

2024-12-05 00:08 UTC, merged